services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    restart: always
    ports:
      - "1883:1883"  # Puerto MQTT estándar
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      
  nodered:
    image: nodered/node-red:latest
    depends_on: 
      - mqtt
    restart: always
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - MQTT_BROKER=${MQTT_BROKER}
      - MQTT_PORT=${MQTT_PORT}
    ports:
      - "1880:1880" # Puerto acceso a Nodered
    volumes:
      - ./node-red-data:/data
      # - ./flows_hivemq.json:/data/flows.json
      # - ./flows_mosquitto.json:/data/flows.json
      #- ./flows.json:/data/flows_runtime.json
      - ./flows.json:/tmp/flows_base.json:ro
    #entrypoint: ["/bin/sh", "/data/init.sh"]
    
    command: >
      sh -c "
      if [ ! -f /data/flows.json ]; then
        cp /tmp/flows_base.json /data/flows.json;
      fi;
      npm start -- --userDir /data
      "
volumes:
  nodered_data:
  mosquitto_data:
     
     

