services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    ports:
      - "1883:1883"  # Puerto MQTT estándar
    environment:
      - TZ=America/Argentina/Buenos_Aires
  nodered:
    image: nodered/node-red
    environment:
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "1880:1880" # Puerto acceso a Nodered
    volumes:
      - ./node-red-data:/data
      - /dev/snd:/dev/snd
    links:
      - mqtt

